events {
  worker_connections 1024;
}

http {

  server {
    listen 9000 default_server;
    access_log /dev/stdout;
    error_log /dev/stderr;

    root /code/backend;
    server_name _;

    location ^~ /function {
      deny all;
      return 403;
    }

    location / {
      try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
      fastcgi_pass 127.0.0.1:9527;
      fastcgi_index index.php;
      include /etc/nginx/fastcgi_params;

      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

      fastcgi_read_timeout 180;

      fastcgi_param DB_HOST "PHDB_HOST";
      fastcgi_param DB_NAME "PHDB_NAME";
      fastcgi_param DB_USER "PHDB_USER";
      fastcgi_param DB_PASSWORD "PHDB_PASSWORD";

      fastcgi_param FRONTEND_URL "PHFRONTEND_URL";
      fastcgi_param ALLOW_NO_ORIGIN_REQUESTS "PHALLOW_NO_ORIGIN_REQUESTS";

      fastcgi_param TZ "PHTZ";
      fastcgi_param GLOBAL_SALT_3 "PHGLOBAL_SALT_3";

      fastcgi_param DEFAULT_FIELDS "PHDEFAULT_FIELDS";

      fastcgi_param FILE_ENABLED "PHFILE_ENABLED";
      fastcgi_param ALLOW_SIGN_UP "PHALLOW_SIGN_UP";
      fastcgi_param CUSTOMIZE_FIELDS "PHCUSTOMIZE_FIELDS";

      fastcgi_param PIN_EXPIRE_TIME "PHPIN_EXPIRE_TIME";
      fastcgi_param LOG_EXPIRE_TIME "PHLOG_EXPIRE_TIME";

      fastcgi_param BLOCK_IP_TRY "PHBLOCK_IP_TRY";
      fastcgi_param BLOCK_IP_TIME "PHBLOCK_IP_TIME";

      fastcgi_param BLOCK_ACCOUNT_TRY "PHBLOCK_ACCOUNT_TRY";
      fastcgi_param ACCOUNT_BAN_TIME "PHACCOUNT_BAN_TIME";

      fastcgi_param SERVER_TIMEOUT "PHSERVER_TIMEOUT";
      fastcgi_param PBKDF2_ITERATIONS "PHPBKDF2_ITERATIONS";
    }

    location ~ /\.ht {
      deny all;
    }
  }
}