[global]
pid = /tmp/php7.4-fpm.pid
error_log = /tmp/php7.4-fpm.log

[www]
user = www-data
group = www-data
listen = 127.0.0.1:9527
listen.owner = www-data
listen.group = www-data
pm = static
pm.max_children = 5